name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'recursive'
    - name: Get Ninja
      uses: turtlesec-no/get-ninja@main
    - name: Install Dependencies
      shell: bash
      run: |
          sudo apt-get -qq update && sudo apt-get -qq upgrade
          sudo apt-get install -qq -y libx11-dev libssl-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev
          wget -q https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Linux-Release-x64-libstdc++.zip
          mkdir $HOME/deps && mkdir $HOME/deps/skia && unzip -q -d $HOME/deps/skia Skia-Linux-Release-x64-libstdc++.zip
    - name: Generate Makefiles
      shell: bash
      run: |
        export enable_ccache=on
        CC=gcc-12 CXX=g++-12 cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_TESTS=OFF \
          -DENABLE_BENCHMARKS=OFF \
          -DENABLE_PSD=ON \
          -DFULLSCREEN_PLATFORM=ON \
          -DENABLE_DESKTOP_INTEGRATION=ON \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$HOME/deps/skia \
          -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
          -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
          -DENABLE_UI=ON \
          -DENABLE_CCACHE=$enable_ccache
    - name: Compile
      shell: bash
      run: |
        cd build && ninja && find bin/ -maxdepth 1 -type f -exec strip {} \; && find bin/ -maxdepth 1 -type f -exec chmod +x {} \;
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: aseprite
        path: build/bin
        if-no-files-found: error
